cmake_minimum_required(VERSION 4.1)
project(cteht C)

set(CMAKE_C_STANDARD 11)

add_executable(cteht
        ex3.c
        ex1.c
        ex2.c
        ex4.c
        ex5.c
        ex6.c
        ex7.c
        ex8.c
        ex9.c
        ex10.c
        ex11.c
        ex12.c
        ex13.c
        ex14.c
        ex15.c
        ex16.c
        ex17.c
        ex18.c
        ex19.c
        ex20.c
        ex20_debug.c
        ex20_debug.h.c
        ex21.c
)
